name: Untrusted Pipeline

permissions: {}

on:
  workflow_dispatch: {}

jobs:
  call-trusted-pipeline:
    permissions:
      contents: read
    uses: laerson/ssip-trusted-pipeline/.github/workflows/sast.yml@main
