name: Untrusted Pipeline

permissions: {}

on:
  workflow_dispatch: {}

jobs:
  call-trusted-pipeline:
    permissions:
      contents: read
      actions: read
    uses: laerson/ssip-trusted-pipeline/.github/workflows/build.yml@main
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}
    secrets:
      username: laerson
      password: ${{ secrets.GITHUB_TOKEN }}