name: Untrusted Pipeline

permissions: {}

on:
  workflow_dispatch: {}

jobs:
  call-trusted-pipeline:
    permissions:
      contents: read
      actions: read
      packages: write
    uses: laerson/ssip-trusted-pipeline/.github/workflows/trusted-pipeline.yml@main
    with:
      temp-registry: ssip-hub.lsd.ufcg.edu.br
    secrets:
      intermediary-registry-username: ${{ secrets.TEMP_REP_USERNAME }}
      intermediary-registry-password: ${{ secrets.TEMP_REP_PASSWORD }}